// Generated by CoffeeScript 1.4.0
var T, Twit, fs, gm, io;

io = require('socket.io').listen(80);

io.set('log level', 2);

Twit = require('twit');

T = new Twit({
  consumer_key: 'l5z7NIAbLNwqYNC6L3FZA',
  consumer_secret: 'jxYxJNnj4VlShIyQ6xtyufhXU4YY3T7n3VsXY4U',
  access_token: '83815996-wdFgKPMmHuuwqcdv7kotExLRh7iYOINP6I2WdcVVs',
  access_token_secret: 'T1PiQ2mddLfcoCGPyhPwJb1o3u5idenCBwBFPOEo'
});

fs = require('fs');

gm = require('gm');

io.sockets.on('connection', function(socket) {
  var stream;
  stream = T.stream('statuses/sample', {
    lang: "en"
  });
  return stream.on('tweet', function(tweet, i) {
    var hashtag, hashtags, _i, _len, _ref;
    if (tweet.entities.hashtags) {
      hashtags = [];
      _ref = tweet.entities.hashtags;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        hashtag = _ref[_i];
        if (hashtag.text.toLowerCase() !== 'wesleyfollowspree') {
          hashtags.push(hashtag.text.toLowerCase());
        }
      }
      if (hashtags.length > 1) {
        return socket.emit('tweet', hashtags);
      }
    }
  });
});
